#!/usr/bin/env bash

echo "== sync"

#Exit immedietly if any command returns a non zero status
set -e

#Check for bucket name
if [ -z "$1" ]; then
    echo "No bucket name provided. eg. ./bucket my-bucket-name"
    exit 1
fi

#Check for filename prefix
if [ -z "$2" ]; then
    echo "No filename prefix provided. eg. ./bucket my-bucket-name my-filename-prefix"
    exit 1
fi


BUCKET_NAME=$1
FILENAME_PREFIX=$2


#Where we store these files
OUTPUT_DIR="/tmp/s3-bash-scripts"

#Remove folder if already exists

rm  -r  $OUTPUT_DIR

#Lets create output folder
mkdir -p $OUTPUT_DIR



#Random amount numb generate = numb files created 

NUM_FILES=$((RANDOM %6 + 5))

 for (( i=1; i<=NUM_FILES; i++ )); do
  # Generate a random filename
  FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

  # Generate random data and write it to the file
  dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1 )) 2>/dev/null

done

tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files